spring.application.name=Lab4
spring.data.mongodb.auto-index-creation=true

# mongodb
spring.data.mongodb.uri=mongodb+srv://laidaynao901:S2bMWiZCDIqhES1Q@cluster0.qv15ecd.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=IE303-Lab4

spring.thymeleaf.prefix=classpath:/image

api.prefix=/api/v1
